# Generated by Django 6.0 on 2025-12-19 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField(help_text='The mission description for Robo-X')),
                ('code', models.TextField(help_text='The C++ code containing the bug')),
                ('hint', models.TextField(help_text='The hint shown when the user is wrong')),
                ('order', models.IntegerField(default=0, help_text='Order in which mission appears')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='game.question')),
            ],
        ),
    ]
