# Generated by Django 6.0 on 2026-01-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='image',
            field=models.ImageField(upload_to='chapters/'),
        ),
    ]
