# Generated by Django 6.0 on 2026-01-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_chapter_is_locked_alter_chapter_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
